<? // языковой файл для шаблона компонента
if ( !defined("GY_GLOBAL_FLAG_CORE_INCLUDE") && (GY_GLOBAL_FLAG_CORE_INCLUDE !== true) ) die( "gy: err include core" );

$mess['rus'] = array(
    'title-edit-file' => 'Работа со страницами сайта',
    'text-input-url-page' => 'Укажите путь к страницы над которой хотите произвести действие',
    'ok' => 'ok',
    'add-ok' => 'Страница успешно создана',
    'del-ok' => 'Страница успешно удалена',
    'text-edit-page' => 'Вы редактируете страницу',
    'err' => 'Произошла ошибка',
    'edit-ok' => 'Страница успешно изменена',
    'title-action-5' => 'Конструктор страницы (редактирование по компонентам)',
    'title-action-4-show-page' => 'Посмотреть страницу',
    'title-delete-page' => 'Удалить страницу',
    'title-edit-page' => 'Изменить страницу',
    'title-add-page' => 'Создать страницу (заменит если уже есть)',
    'text-include-components' => 'На странице подключено компонентов - ',
    'text-include-this-component' => 'Компонент - ',
    'name-template' => 'Имя шаблона:',
    'params-component' => 'Параметры вызова компонента:',
    'param-name' => 'Название параметра',
    'param-value' => 'Значение параметра',
    'text-button-save' => 'Сохранить',
    'text-button-save2' => 'Сохранить страницу',
    'text-button-del-component' => 'Удалить этот компонент (и сохранить изменения)',
    'include-component' => 'Вызываемый компонент страницы №',
    'text-button-up-component' => 'Переместить компонент выше (и сохранить изменения)',
    'text-button-down-component' => 'Переместить компонент ниже (и сохранить изменения)',
    'add-component' => 'Добавить компонент ниже',
    'warning-text-1' => 'Внимание! код страницы оформленный не компонентами уничтожится.',
    'title-action-8' => 'Добавление нового компонента на страницу',
    'name-new-component' => 'Введите имя компонента',
    'name-new-template' => 'Введите имя шаблона компонента (0 - по умолчанию)',
    'next' => 'Далее',
    'not-component' => 'Выбранного компонента не существует',
    'next_final' => 'Добавить компонент',
    'this_component' => 'Выбран компонент',
    'this_v_component' => 'Версия компонента',
    'this_component_text_info' => 'Описание компонента',
    'this_template_component' => 'Выбранный шаблон компонента'
);

